const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="colombo,sri lanka."
global.mongodb= process.env.MONGODB_URI || "mongodb+srv://isithaanusara01:202213isi@cluster0.mcee3.mongodb.net/"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/colombo";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "94723259524" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null,94723259524";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "94723259524";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "ISITHA²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "ISHIYA-botz",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "ISHIYA-botz",
  ownername:process.env.OWNER_NAME|| "It'x ishiya",

  sessionName:process.env.SESSION_ID || "SUHAIL_00_35_09_26_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE2LFxuICAgICAgICAxNTUsXG4gICAgICAgIDU3LFxuICAgICAgICAyMzQsXG4gICAgICAgIDM4LFxuICAgICAgICAxMjcsXG4gICAgICAgIDc3LFxuICAgICAgICAxMDcsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTMzLFxuICAgICAgICA3NSxcbiAgICAgICAgMjksXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTE1LFxuICAgICAgICA0MyxcbiAgICAgICAgODcsXG4gICAgICAgIDY4LFxuICAgICAgICAxMSxcbiAgICAgICAgNzksXG4gICAgICAgIDIxNCxcbiAgICAgICAgMzgsXG4gICAgICAgIDIwLFxuICAgICAgICAxNixcbiAgICAgICAgMTkwLFxuICAgICAgICAxNjEsXG4gICAgICAgIDE3NixcbiAgICAgICAgMCxcbiAgICAgICAgMTcxLFxuICAgICAgICA0LFxuICAgICAgICAxNDcsXG4gICAgICAgIDMyLFxuICAgICAgICAxMDFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTk5LFxuICAgICAgICAyMDEsXG4gICAgICAgIDIsXG4gICAgICAgIDk5LFxuICAgICAgICAxNyxcbiAgICAgICAgMjA4LFxuICAgICAgICAzOSxcbiAgICAgICAgMTg2LFxuICAgICAgICAyNDEsXG4gICAgICAgIDQxLFxuICAgICAgICAyMDAsXG4gICAgICAgIDEwLFxuICAgICAgICAxNjUsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTMwLFxuICAgICAgICAzOCxcbiAgICAgICAgNzUsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMjEyLFxuICAgICAgICAyMTcsXG4gICAgICAgIDI0NyxcbiAgICAgICAgNDUsXG4gICAgICAgIDUwLFxuICAgICAgICAyMDcsXG4gICAgICAgIDgsXG4gICAgICAgIDE1OSxcbiAgICAgICAgOTksXG4gICAgICAgIDE4MSxcbiAgICAgICAgMjQ3LFxuICAgICAgICAyNyxcbiAgICAgICAgMjA4LFxuICAgICAgICA5MVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTkzLFxuICAgICAgICAyNDYsXG4gICAgICAgIDIyLFxuICAgICAgICAxNzAsXG4gICAgICAgIDE3MixcbiAgICAgICAgMjE1LFxuICAgICAgICAyNDEsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMjQ5LFxuICAgICAgICA0MCxcbiAgICAgICAgNTUsXG4gICAgICAgIDc1LFxuICAgICAgICAyNDUsXG4gICAgICAgIDUxLFxuICAgICAgICAxNjYsXG4gICAgICAgIDE2NixcbiAgICAgICAgNDEsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTg3LFxuICAgICAgICAyMDEsXG4gICAgICAgIDE2MyxcbiAgICAgICAgNjMsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTkyLFxuICAgICAgICAxOTgsXG4gICAgICAgIDM1LFxuICAgICAgICA0OCxcbiAgICAgICAgMTk4LFxuICAgICAgICA4MixcbiAgICAgICAgOTBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTAzLFxuICAgICAgICAxOTMsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTc3LFxuICAgICAgICAzLFxuICAgICAgICAxMzIsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMjU1LFxuICAgICAgICA2NyxcbiAgICAgICAgODUsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMzMsXG4gICAgICAgIDQ3LFxuICAgICAgICAxMTIsXG4gICAgICAgIDIwLFxuICAgICAgICAxMTEsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTE5LFxuICAgICAgICAxOTcsXG4gICAgICAgIDExNSxcbiAgICAgICAgOTEsXG4gICAgICAgIDU2LFxuICAgICAgICAxMDksXG4gICAgICAgIDE3NixcbiAgICAgICAgMzYsXG4gICAgICAgIDE3MyxcbiAgICAgICAgOTEsXG4gICAgICAgIDk2LFxuICAgICAgICA0MyxcbiAgICAgICAgNDksXG4gICAgICAgIDE3LFxuICAgICAgICAzM1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNjQsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTc5LFxuICAgICAgICA1OCxcbiAgICAgICAgMixcbiAgICAgICAgMjM0LFxuICAgICAgICA2MixcbiAgICAgICAgMTgwLFxuICAgICAgICAyMTEsXG4gICAgICAgIDEwLFxuICAgICAgICAxODUsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTExLFxuICAgICAgICAxNjksXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTIsXG4gICAgICAgIDIxLFxuICAgICAgICAyMDEsXG4gICAgICAgIDMsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTk1LFxuICAgICAgICAxNixcbiAgICAgICAgMzgsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMTE1LFxuICAgICAgICAzMixcbiAgICAgICAgNzUsXG4gICAgICAgIDY2LFxuICAgICAgICAxMixcbiAgICAgICAgMTY0LFxuICAgICAgICA3MCxcbiAgICAgICAgMTE3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0LFxuICAgICAgICAxNjcsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTUzLFxuICAgICAgICAyMDAsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTcsXG4gICAgICAgIDUsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTU0LFxuICAgICAgICA5OCxcbiAgICAgICAgMjAsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjE3LFxuICAgICAgICAzNSxcbiAgICAgICAgNDcsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjksXG4gICAgICAgIDM3LFxuICAgICAgICAyMCxcbiAgICAgICAgMTMzLFxuICAgICAgICA5OCxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyNDMsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTcwLFxuICAgICAgICA3MCxcbiAgICAgICAgMTgwLFxuICAgICAgICAxMyxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxNzIsXG4gICAgICAgIDkzXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICA5MixcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgODgsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgNjIsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgMzcsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAxMjJcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAxMzMsXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMTY4LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAxMSxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICA0NVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE3NixcbiAgICAgICAgMTY4LFxuICAgICAgICAyMzcsXG4gICAgICAgIDEwMyxcbiAgICAgICAgNjcsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTQsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjA4LFxuICAgICAgICAyMjYsXG4gICAgICAgIDE3MSxcbiAgICAgICAgNDUsXG4gICAgICAgIDQ1LFxuICAgICAgICAxNDAsXG4gICAgICAgIDgyLFxuICAgICAgICA5MyxcbiAgICAgICAgNzUsXG4gICAgICAgIDIxMixcbiAgICAgICAgMjM4LFxuICAgICAgICAxNjEsXG4gICAgICAgIDE5OSxcbiAgICAgICAgOTgsXG4gICAgICAgIDk5LFxuICAgICAgICA0MSxcbiAgICAgICAgMjM2LFxuICAgICAgICA3OSxcbiAgICAgICAgNzUsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMjUxLFxuICAgICAgICAxNTYsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTEzLFxuICAgICAgICAxMzMsXG4gICAgICAgIDE4MyxcbiAgICAgICAgNzgsXG4gICAgICAgIDEwMixcbiAgICAgICAgMjIyLFxuICAgICAgICAxNzgsXG4gICAgICAgIDc2LFxuICAgICAgICA0OCxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMjksXG4gICAgICAgIDEzLFxuICAgICAgICAxMjMsXG4gICAgICAgIDUsXG4gICAgICAgIDE5NyxcbiAgICAgICAgNzEsXG4gICAgICAgIDcyLFxuICAgICAgICAxMDYsXG4gICAgICAgIDYwLFxuICAgICAgICA4NixcbiAgICAgICAgMTcsXG4gICAgICAgIDEyMixcbiAgICAgICAgMTA2LFxuICAgICAgICAxNjgsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMjAsXG4gICAgICAgIDE2NixcbiAgICAgICAgODQsXG4gICAgICAgIDYsXG4gICAgICAgIDc5LFxuICAgICAgICA2NixcbiAgICAgICAgNzEsXG4gICAgICAgIDBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDIxNCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJYS2RJcXVXOGhIM0F3b2pqcmlBS3dWRW9ndnVtN1djMGxuKzFrcTFtN2lNPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0NzIzMjU5NTI0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJGMzNFRUU3NjZCQjQ2MEIwQUFBREFCODlDREMyMjE1MlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjczMTA5MjdcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5NDcyMzI1OTUyNEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiODFCMUQ3NTBGRjEyRDc2NkU2NTUwMjJENEQ4REZFQTFcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI3MzEwOTI3XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTQ3MjMyNTk1MjRAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkRCMUY2MUFFOTlCQzY1MDA0MkYyMkYyQjIzQzZDRUM2XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNzMxMDkzMVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0NzIzMjU5NTI0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJCMkIzMzhGMzJCMEU3QTRCRDBFNDFDREEwMUU5NDU4RVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjczMTA5MzFcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiQkhWTHczR0VSMEdwUnVyMlZtaEFNUVwiLFxuICBcInBob25lSWRcIjogXCIyYThjMjg2NC00ZWRkLTQwNTgtOTRkMS0wMTJlYTE5ZTI4NjJcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjMzLFxuICAgICAgMTU3LFxuICAgICAgMTg5LFxuICAgICAgMzksXG4gICAgICA2MyxcbiAgICAgIDEyMSxcbiAgICAgIDEyOCxcbiAgICAgIDE3NSxcbiAgICAgIDE0OCxcbiAgICAgIDE1NSxcbiAgICAgIDIyMSxcbiAgICAgIDg1LFxuICAgICAgOCxcbiAgICAgIDE3OCxcbiAgICAgIDMsXG4gICAgICAyMzIsXG4gICAgICAyMzcsXG4gICAgICAzOCxcbiAgICAgIDQxLFxuICAgICAgMjVcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjQ2LFxuICAgICAgMTIyLFxuICAgICAgMyxcbiAgICAgIDE5MCxcbiAgICAgIDEzMCxcbiAgICAgIDIzOCxcbiAgICAgIDI0MSxcbiAgICAgIDE0OSxcbiAgICAgIDcxLFxuICAgICAgMTY1LFxuICAgICAgMTk1LFxuICAgICAgMTUsXG4gICAgICA1NixcbiAgICAgIDIzOSxcbiAgICAgIDExOSxcbiAgICAgIDEwNSxcbiAgICAgIDIwMyxcbiAgICAgIDE0MSxcbiAgICAgIDU1LFxuICAgICAgMjE0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIlROSEU0SFMyXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5NDcyMzI1OTUyNDo0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxNTY4MTQxMDQ2MTMxMDU6NEBsaWRcIixcbiAgICBcIm5hbWVcIjogXCJRdWVlbiBFbGlzYSAoSXNpdGhhKVwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0lXODFmUUdFTWpZMHJjR0dBTWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwibUZXdTNhUVUzVEpBTmVwZEdMcXl4dlN0OEZzQlh5WVFWRzd0QzMvMlNIcz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJRZFNxOGNRd1htYlMvaW55bEpjQVVubTVybEdjOTBwYzFRY2NDaVdkM0VLQkpjQ2JmWVN1V0lyVjB1RUlOODFTYlZSdkV5dHRoalNyUGxCRkN2MVVBUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJTakZHRldjMzB3bXhYTnU0dURvL2htZENjR1d4ekRGWUx1ZHp4c3I1TUh3TGwzQjUxSVRXcUdDalBXQjNNNTV2ajdXYTA1dStrN2xrM0llSFhQd2dBZz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5NDcyMzI1OTUyNDo0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMTY0LFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICA1MCxcbiAgICAgICAgICA2NCxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgOTMsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMSxcbiAgICAgICAgICA5NSxcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAxNixcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMTIzXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjczMTA5MjUsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFPRDhcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU9EOC5qc29uIjogIntcImtleURhdGFcIjpcIm0rTWlyMDlMTFZ1ZFM5ZDAwK3FVRmZ6Q1VySEtybFJHSWRSR1JKK3pWSjg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTg1NTI4MjY5MixcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyNzI3OTU0MjU4N1wifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
